Death System
FarazzShaikh/LunarLander pull request #43
Opened 2020-10-24 17:12 UTC by KishanBapodra

Is what I did right not too sure 
I added code for listening to game over event in main.js need to figure out how to remove the player though

2020-10-24 19:36 UTC, FarazzShaikh commented
Make the changes and then you can work on the damage system that will integrate with the shooting system

2020-10-25 07:22 UTC, FarazzShaikh requested changes

2020-10-25 08:54 UTC, KishanBapodra commented on server/src/main.js
> +
Alright so its like if didcollide is true then its emitting the server hit ground.req and that is acknowledged in the client main.js?

2020-10-25 08:57 UTC, KishanBapodra commented on server/src/main.js
> +
or is it the other way around as in when there is a collision its acknowledged i.e. emit(REQUE.SER.HI.GROUN.ACK) and on the client side in main it listens for the server,hit,gro.req

2020-10-25 09:48 UTC, FarazzShaikh commented on server/src/main.js
> +
The server will emit `EVENT.SERVER_PLAYER_HIT_GROUND.req` the client will listen for this event and then respond with an acknowledgement -  `EVENT.SERVER_PLAYER_HIT_GROUND.ack`. Then the server will listen for this acknowledgement and then delete the player from the server and send an updated player list to everyone else by emitting `EVENTS.SERVER_UPDATE_PLAYERS`. The other players will listen for this and update their player lists accordingly.

2020-10-25 12:52 UTC, FarazzShaikh approved these changes

2020-10-25 12:53 UTC, merged